apiVersion: v1
kind: Service
metadata:
  name: cocs-gate
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: gsai
    component: cocs
  ports:
    - port: {{ .Values.cocs.port }}
      targetPort: {{ .Values.cocs.port }}
      name: constraint
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cocs-gate
  namespace: {{ .Values.namespace }}
  labels:
    app: gsai
    component: cocs
spec:
  replicas: {{ .Values.cocs.replicas }}
  selector:
    matchLabels:
      app: gsai
      component: cocs
  template:
    metadata:
      labels:
        app: gsai
        component: cocs
    spec:
      containers:
        - name: cocs
          image: "{{ .Values.images.repository }}:{{ .Values.images.tag }}"
          command: ["python", "-m", "cocs.m_valid"]
          env:
            - name: CKS_MODE
              value: {{ .Values.cocs.mode }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.cocs.port }}
