apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-controller
  namespace: {{ .Values.namespace }}
  labels:
    app: gsai
    component: governance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gsai
      component: governance
  template:
    metadata:
      labels:
        app: gsai
        component: governance
    spec:
      containers:
        - name: governance
          image: "{{ .Values.images.repository }}:{{ .Values.images.tag }}"
          command: ["python", "-m", "governance.ccp"]
          env:
            - name: CKS_MODE
              value: {{ .Values.mode }}
            - name: CCP_ENABLED
              value: "{{ .Values.governance.ccp_enabled }}"
            - name: MG_ENABLED
              value: "{{ .Values.governance.mg_enabled }}"
            - name: RAL_ENABLED
              value: "{{ .Values.governance.ral_enabled }}"
