apiVersion: v1
kind: Service
metadata:
  name: ck-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ck
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
